name: flutter_base_template
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  auto_route: ^8.1.3

  # API
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  ua_client_hints: ^1.2.2

  # Generating Code
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Logger
  logger: ^2.3.0

  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  flutter_secure_storage: ^9.2.0

  # UI
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

  # Toast
  fluttertoast: ^8.2.5

  # Secrets
  flutter_dotenv: ^5.1.0

  # Localization
  intl: ^0.19.0

  # Util
  enum_to_string: ^2.0.1

  # Mock API
  http_mock_adapter: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^4.0.0

  # State management
  riverpod_generator: ^2.4.0

  # Routing
  auto_route_generator: ^8.0.0

  # Asset
  flutter_gen_runner: ^5.4.0

  # API
  retrofit_generator: ^8.1.0

  # Generating Code
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # Test
  # mocktail: ^1.0.3
  # mocktail_image_network: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/
    - assets/remote_mock_data/demo/
    - assets/local_mock_data/

  fonts:
    - family: Japanese
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: English
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 500
